# Define sweep config

method: grid
name: sweep_1_classification
parameters: 
    NUM_GRAPHS_PER_GRAPHON: 
        values: 
            - 10
            - 50
            - 100
    NUM_NODES: 
        values: 
            - None
            - 100 
            - 250
            - 500
    DATA:  
        values:
            - [[], ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']]
            - [[], ['1', '2', '3', '4', '5']]
    N0:
        values:
            - 10
            - 20
            - 30
            - 50
     


