# Define sweep config

method: grid
name: clustering_exp
parameters: 
    NUM_GRAPHS_PER_GRAPHON: 
        values: 
            - 50
            - 100
            - 250
    NUM_NODES: 
        values: 
            - None
            - 100 
            - 300
    DATA:  
        values:
            - [[], ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']]
            - [[], ['1', '2', '3', '4', '5']]
    N0:
        values:
            - 10
            - 20
            - 30 
            - 40
     


