# Define sweep config

method: grid
name: sweep_1_classification
parameters: 
    # config: 
    #     value: 
    #         - config.yaml
    NUM_GRAPHONS: 
        values: 
            - 4
            - 6
    NUM_GRAPHS_PER_GRAPHON: 
        values: 
            - 50
            - 100
    NUM_NODES: 
        values: 
            - None
            - 100 
            - 300
     


