# Define sweep config

method: grid
name: synth_no_aug
parameters: 

    # NUM_GRAPHS_PER_GRAPHON: 
    #     values: 
    #         - 25
    #         - 50

    NUM_NODES: 
        values: 
            - None
            - 100 
            - 450
    # USE_INTERPOLATION:
    #     values:
    #         - True
    #         - False

    DATA:  
        values:
            - [[], ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']]
            - [[], ['1', '2', '3', '4', '5']]
    N0:
        values:
            - 5
            - 7
            - 9
            - 11
            - 13
            - 30
    # AUGMENT_DATA:
    #     values:
    #         - True 
    #         - False

     


